### ISSUE TITLE
jbosstools/jbosstools-base related issues

### ISSUE THREAD

**Issue by jyoti-26** [jbosstools/jbosstools-openshift#1477]
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.jboss.tools.common.core 3.8.3.qualifier
[ERROR]   Missing requirement: org.jboss.tools.common.core 3.8.3.qualifier requires 'bundle org.jboss.tools.foundation.core 1.3.3' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.jboss.tools.common.plugins:org.jboss.tools.common.core:3.8.3-SNAPSHOT @ E:\Jyoti\jbosstools-base\common\plugins\org.jboss.tools.common.core\pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by bdshadow** [comment]
@jyoti-26 i suspect, you want to start contributing to this project, you need[ jbosstools-base](https://github.com/jbosstools/jbosstools-base) and [jbosstools-server ](https://github.com/jbosstools/jbosstools-server) be imported into your workspace too. Please, also read [Contribute fixes and features](https://github.com/jbosstools/jbosstools-openshift#contribute-fixes-and-features) section. It describes the way to create issue in [JBoss Tools JIRA ](https://issues.jboss.org/browse/JBIDE). We don't use github issues tab for this purpose.
So if you have any questions about contributing, [our irc and mailing lists](http://tools.jboss.org/community/) are good starting points. If you want to create an issue in jira, please, provide more info of what you're doing that causes the problem (not just stacktrace).
