### ISSUE TITLE
Error While Executing jbosstools/jbosstools-openshift 

### ISSUE THREAD

**Issue by jyoti-26** [jbosstools/jbosstools-openshift#1478]
To build jbosstools-openshift-4.4.3  I followed following steps 
1. I clone jbosstools-base and jbosstools-server which are required for the building  jbosstools-openshift-4.4.3.
2. while executing the jbosstools-base I got error "Missing requirement: org.jboss.tools.common.core 3.8.3.qualifier requires 'bundle org.jboss.tools.foundation.core 1.3.3' but it could not be found".

3. I build the org.jboss.tools.foundation.core 1.3.3 plugin and add into eclipse plugin folder  and restart the eclipse IDE still facing the isuue.

**Comment by bdshadow** [comment]
@jyoti-26 please, don't open issue here. See my comment to your previous issue: https://github.com/jbosstools/jbosstools-openshift/issues/1477#issuecomment-296948597. You can use irc or mailing lists for such questions
