### ISSUE TITLE
BrowserContainsText - refreshig page when JS is not loaded yet

### ISSUE THREAD

**Issue by vprusa** [jbosstools/jbosstools-openshift#1664]
Condition test [BrowserContainsText](https://github.com/jbosstools/jbosstools-openshift/blob/master/test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/BrowserContainsText.java#L36) is not stable for pages where JS is loading data after page is loaded. G.e. redirecting OSIO login page using different account provider (jboss developer) results in refreshing already loaded page (Red Hat login page) instead of refreshing page for which there was a redirection attempt (jboss developer). In case of trying to set URL in code validity of page is lost (most likely because CSFR token is originally sent with redirecting using JS .click() ).
Solution imo can be by override method arguments to add
```private boolean refresh;``` with  
```public BrowserContainsText(String url, String text, boolean refresh) { ... }```
 where page refresh will happen only when by default ```refresh=true```  .
PR in progress..

**Comment by adietish** [comment]
@vprusa thx for reporting! I moved this issue to our jira for consistency (so that we have all issue over in our JIRA): https://issues.jboss.org/browse/JBIDE-25747
